### PR TITLE
Adding Sweetalert

### PR DESCRIPTION
**Pull request by adzimzf**
I thinks with this sweetalert AdminLTE will be better look.
I wish you'll marge my pull,
Actualy this plugin isn't mine, but this is free plugins.

Thanks You So Much AdminLTE

### CODE REVIEW

**Comment by MarksEliel** [comment]
I also agree, currently use Sweet Alert added manually, most have something native would be great.

**Comment by MarksEliel** [comment]
I think something like that would also be good:
http://prntscr.com/cyuzbo

**Comment by adzimzf** [comment]
Yeah, great to change position of alert,

**Comment by herberthudson** [comment]
:+1:

**Comment by almasaeed2010** [comment]
Hello @adzimzf,

You added a link to UI/Alert.html, but I can't find that page. Could you please add that here?

Thanks!

**Pull request closed without merging**
