### PR TITLE
#1947   fixed content-wrapper height

### PR DESCRIPTION
**Pull request by shiri1248**
#1947 fixed

### CODE REVIEW

**Comment by rodruiz** [comment]
Tested and it fixed the issue.

**Comment by rodruiz** [comment]
@shiri1248 
but you have to update [Layout.js](https://github.com/almasaeed2010/AdminLTE/blob/master/build/js/Layout.js#L100) too, right?

**Comment by shiri1248** [comment]
yes @rodruiz  will update soon

**Comment by shiri1248** [comment]
@rodruiz  updated the layout.js , Please review the changes

**Comment by almasaeed2010** [comment]
Thanks

**Pull request merged**
