### PR TITLE
Enable explicit box activation

### PR DESCRIPTION
**Pull request by pbihler**
If you insert a box manually into the DOM (e.g. triggered by an ajax-event), you have to activate the box controls explicitly. This can now be done via `.activateBox()`

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Thanks

**Comment by mortasoft** [comment]
How use it? I'm trying, but doesn't work. Do you have an example?

**Comment by pbihler** [comment]
```js
box = $('<div class="box">
      <div class="box-header with-border"><h3 class="box-title">Bla</h3></div>
      <div class="box-body">Blubb</div>
  </div>');

box.insertAfter('#anchor');
box.activateBox();

```

**Comment by almasaeed2010** [comment]
@mortasoft please make sure that you update AdminLTE to latest release first. the release that support this feature will be 2.1.2

**Pull request merged**
