### PR TITLE
Allow collapsible form in box

### PR DESCRIPTION
**Pull request by fschaeffer**
See issue #523

### CODE REVIEW

**Comment by almasaeed2010** [comment]
What happens if we just remove ```>``` instead of adding the ```> form``` to the query?

**Comment by fschaeffer** [comment]
Hello,

I just tested your suggestion and it works, but I have no idea whether this would cause any other sideeffects. Was there a special reason why you chose the direct children selector?

**Comment by almasaeed2010** [comment]
What happens is that we would reproduce an issue that we fixed long ago #321. 

I'll merge this PR then since it sounds like the best solution. Thank!

**Comment by fschaeffer** [comment]
OK, for the moment it seems like the best solution, experienced some lag in the slideUp-effect but this was not reproducable anymore ...

BTW: I also added the data-collapse to the header so the whole header is acting as trigger for the collapse (sort of accordeon) which works nicely but is a very special case.

Thanks for merging

**Pull request merged**
