### PR TITLE
Fixed Issue #1147 - word wrap - treeview menu

### PR DESCRIPTION
**Pull request by tannakartikey**
Added `white-space: normal` to treeview-menu class in sidebar.
Now overflowing text will be shown in the next line.
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

### CODE REVIEW

**Comment by tannakartikey** [comment]
@almasaeed2010 have I done it in the correct way?

**Comment by almasaeed2010** [comment]
How does that affect the transition from regular sidebar to sidebar-mini?

Thanks!

**Comment by tannakartikey** [comment]
@almasaeed2010 it's working fine. PFA screenshot.
image

**Comment by almasaeed2010** [comment]
Please review #1294

**Pull request closed without merging**
