### PR TITLE
Updated Pace & Created Custom Style

### PR DESCRIPTION
**Pull request by iaesaudi**
- Update to Pace v1.0.2 so there is no errors appears on Safari browsers.
- Modified one of the original styles to be matched with AdminLTE and Works good on both Desktop and Mobile versions.

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Hello,

Did you create a test page to view this before merging?

Thanks for the contribution!

**Comment by iaesaudi** [comment]
I'm already using it on my development site,
If You need to implement it into your HTML pages, just tell me.

I also made it to work with ajax calls.

**Comment by iaesaudi** [comment]
How can I help you to implement it ?

**Comment by almasaeed2010** [comment]
Hello @iaesaudi 

I apologize for the delay! It would be great if you implement it in the examples folder by creating (copying) the blank page and adding pace to it. You could name the new file pace.html. 

Thanks!

**Pull request closed without merging**
