### PR TITLE
Add an option to tweak the animation speed

### PR DESCRIPTION
**Pull request by hienning**
Sometimes we need to customize the animation speed. It will be convenient if there is such an option.

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Thanks for the contribution. I will look into this soon. We may need to add this to animated elements, rather than only the sidebar if there are other elements that use animation.

**Comment by YasserHassan** [comment]
What about making this option a part of the element HTML via a `data` attribute such as `data-aspeed` and the function looks for it on each animated element and uses if found. If not, a default or global setting is used instead.

**Comment by almasaeed2010** [comment]
There aren't many elements that use JS animation so there isn't a need for that. But it is nice to have an option in AdminLTEOptions for the elements that do use animation.

**Comment by almasaeed2010** [comment]
Options have been added to master.

Thank you for the contribution.

**Comment by hienning** [comment]
Good work and appreciated 👍

**Pull request closed without merging**
