### PR TITLE
Fixed a few typos.

### PR DESCRIPTION
**Pull request by homebysix**

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Thanks!

**Comment by kressly** [comment]
is this for 1.3 or for version 2 ?

**Comment by almasaeed2010** [comment]
This is 2.0

**Comment by kressly** [comment]
Oh Ok. Thanks. Now that it has been merged, i guess if we re-download the version 2, we will have all inside right ?

**Comment by almasaeed2010** [comment]
That is correct. As long as you download the master branch.

**Comment by kressly** [comment]
:+1:

**Pull request merged**
