### PR TITLE
Use options for slimscroll (navbarMenuHeight, navbarMenuSlimscrollWidth)

### PR DESCRIPTION
**Pull request by dragon3**
I want to change "navbarMenu" height.

$.AdminLTE.options has options for navbarMenu(slimscroll), 
but two of them ( navbarMenuHeight, navbarMenuSlimscrollWidth ) are not used. so I can't change/override these values.

This pull request enable these options.

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Hello,
I don't see a default value or the options added to ```$.AdminLTE``` object. I will provide this option in v2.1.0. I appreciate your contribution. Thank you!

**Comment by almasaeed2010** [comment]
Oh I am sorry. I misunderstood your request. I get it now.

I can't merge your PL because there are multiple changes to app.js so I will fix it in the recent version. Sorry again for misunderstanding and thank you!

**Comment by almasaeed2010** [comment]
Fixed in master (v2.1.0)

**Comment by dragon3** [comment]
@almasaeed2010 Thank you so much!

**Pull request closed without merging**
