### PR TITLE
Add all of the plugin/external frontend dependencies using bower

### PR DESCRIPTION
**Pull request by xrogers**
This is initial support for bower for all of the external plugins/libraries.
Includes updated plugins, npm modules and updated demo pages.
The transition isn't finished (more could be done to cleanup everything, especially plugin management in the frontend side with tools like systemjs).
Also, the heavily modified datepicker css has been left intact.
most of the changes could be possibly used in version 3 of the template.

### CODE REVIEW

**Comment by machadogj** [comment]
+1!

**Comment by BobMoutarde** [comment]
+1
Thanks.

**Comment by almasaeed2010** [comment]
Hello @xrogers,

This is great work! We appreciate it. Since I am not adding new features to v2, I am not gonna be able to merge this. However, if you create a new branch with these changes, I will add that branch to our repo and create a "Bower" release. This way people can benefit from it and it won't affect our work plans for v3.

Thanks!

**Comment by jakesyl** [comment]
@almasaeed2010 what happened to the bower release?

**Pull request closed without merging**
