### PR TITLE
Add dropdown menu for user

### PR DESCRIPTION
**Pull request by allaghi**
Hi everyone,
Have a nice day,
I am wondering if you could add dropdwon menu for user beside notification dropdown menu as previous version

### CODE REVIEW

**Comment by dcy** [comment]
I want this too.

**Comment by almasaeed2010** [comment]
Please create an issue instead of a PR.

Thanks!

**Comment by BrianLe1507** [comment]
Hi there, Can I know that dropdown menu is added?

**Comment by REJack** [comment]
> Hi there, Can I know that dropdown menu is added?

This is also on the Project board for v3 and it’s one of the next issues to close 😄

**Pull request closed without merging**
