### PR TITLE
Trigger jQuery-events upon box collapse/expand/remove.

### PR DESCRIPTION
**Pull request by pbihler**
Solves the issue #425.

In addition, it allows to register a handler that really removes "removed" boxes from the DOM (as explained in the documentation of the box events).

### CODE REVIEW

**Comment by YasserHassan** [comment]
Thank you @pbihler.

**Comment by almasaeed2010** [comment]
This would work just fine. However, I'd like to namespace the events to ```lte.box.expand```, ```lte.box.collapse```, and ```lte.box.remove```. Also, these are all post event operations. We'll also need pre event operations. Those would be named ```lte.box.expanded```, ```lte.box.collapsed```, and ```lte.box.removed```. 

Note: the pull request can't currently be merged since it conflicts with recent changes according to Github.

**Comment by pbihler** [comment]
How do you plan to implement pre events? Simply triggering them before the slideUp call does not work, since they are delivered afterwards. 

One possibility would be to rely on a callback, but that is incompatible with the events concept.

Pascal

**Comment by Karmalakas** [comment]
I'm in need of the events also, but one more thing would be really useful - trigger expand/collapse/remove.

**Pull request closed without merging**
