### PR TITLE
Don't hardcode slimscroll options.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by almasaeed2010** [comment]
We'll need a way to pass these options instead of just removing them. Maybe we can introduce slimscroll options to the layout plugin.

**Comment by ADmad** [comment]
Yes introducing options for slimscroll would be the right way but until then removing these hard coded values at least allows one to set required styling through css.

**Comment by almasaeed2010** [comment]
I should test how it would look like with the those options first. Will get back to you soon.

Thanks

**Comment by almasaeed2010** [comment]
doesn't seem to have a major effect by default

**Comment by ADmad** [comment]
To me slimscroll's [default](http://rocha.la/jQuery-slimScroll#highlighter_631965) scrollbar handle seems much better than then the tiny 3px currently set :)

**Comment by ADmad** [comment]
`3px` is way to small and `rgba(0,0,0,0.2)` too light for usability.

**Pull request merged**
