### PR TITLE
Form wizard

### PR DESCRIPTION
**Pull request by paulodealmeida**
I had to use form wizard in my project and I decide to contribute with it. I am not an expert, but it is a start.

### CODE REVIEW

**Comment by MichalMajer** [comment]
My future project would so appreciate this functionality. :+1:

**Comment by paulodealmeida** [comment]
Thanks @MichalMajer , but it need some design improvements.

**Comment by MichalMajer** [comment]
I was thinking about implemeting something like http://dobtco.github.io/formbuilder/ into AdminLTE myself. Looks nice.

**Comment by paulodealmeida** [comment]
Uau, this is a good stuf! I will try to implement more html improvements.

**Comment by almasaeed2010** [comment]
Thanks for your effort. We are currently refraining from adding new features to version 2. This feature will be customized and added to v3.

We appreciate your contribution!

**Pull request closed without merging**
