### PR TITLE
SASS Support

### PR DESCRIPTION
**Pull request by karthilxg**
1. Added SASS support for AdminLTE styles.
2. Included Bootstrap-SASS version.
3. Updated Grunt task to run the SASS compiler.
4. Tested the Application with the new style.

Note: There are minor difference in the final output (AdminLTE.css) formatting, SASS updates the colors from #ffffff to #FFF etc.

https://www.diffchecker.com/mshpedmn

### CODE REVIEW

**Comment by YasserHassan** [comment]
This is a good effort @karthilxg but I am concerned about continuity. My understanding is that if this commit is merged, both the LESS and SASS editions will need to be updated and tested separately from now on with each and every change to keep them both in sync. In #289, @almasaeed2010 mentioned that adding SASS will make it harder for him to maintain the template when updated. In #417 and other similar issues, it was obvious that even maintaining the version number among different package files like `bower.json` is hard for him to manage. With that in mind, I believe that adding SASS (which serves the same purpose of the existing LESS) will be counter productive and its time is better spent enhancing the template and adding new features. Probably a better approach is keeping the SASS as a separate repository.

**Comment by karthilxg** [comment]
@YasserHassan Thanks for the response, since lot of people are moving towards SASS from LESS, I thought that having SASS support would add more popularity and contributions to the project, but I like the idea of maintaining the SASS version as a separate repository.

**Comment by almasaeed2010** [comment]
@YasserHassan has a point. I noticed the interest in SASS increasing and I would love to have the template support it. To your knowledge, are you aware of any script that could automate the process? I know that Bootstrap developers support both SASS and LESS and it would be dull to code everything twice. Do you think they are using some kind of script that would compile SASS to LESS or vice versa?

Thanks @karthilxg for the contribution.

**Comment by karthilxg** [comment]
@almasaeed2010 I have used [less2sass](https://github.com/ekryski/less2sass) script for conversion, as mentioned in the caveats section it's not 100% reliable, we might need to fix the SASS compilation issues manually. 

During the conversion most of the issues were occurred on the following places,
* extend tags
* Using !import overrides
* @inlcude tags (while invoking mixins the args are separated with semicolon)
* @import (reference) tags are not supported (https://github.com/sass/sass/issues/1317)

**Comment by almasaeed2010** [comment]
This seems like it would require time to maintain and unfortunately I don't have that luxury. I appreciate your contribution greatly. Perhaps in a future release I'd make SASS the main preprocessor for AdminLTE.

**Comment by karthilxg** [comment]
`Bootstrap SASS` repo maintains a `convert rake task` for pulling the changes from `bootstrap LESS` master branch and converting LESS files in to equivalent SCSS files.

Can the same process be followed for our case ? 

https://github.com/twbs/bootstrap-sass#upstream-converter

>Keeping bootstrap-sass in sync with upstream changes from Bootstrap used to be an error prone and time consuming manual process. With Bootstrap 3 we have introduced a converter that automates this.

>Note: if you're just looking to use Bootstrap 3, see the installation section above.

>Upstream changes to the Bootstrap project can now be pulled in using the convert rake task.

>Here's an example run that would pull down the master branch from the main twbs/bootstrap repo:

>rake convert
>This will convert the latest LESS to Sass and update to the latest JS. To convert a specific branch or version, pass the branch name or the commit hash as the first task argument:

>rake convert[e8a1df5f060bf7e6631554648e0abde150aedbe4]
>The latest converter script is located here and does the following:

>Converts upstream bootstrap LESS files to its matching SCSS file.
>Copies all upstream JavaScript into assets/javascripts/bootstrap, a Sprockets manifest at assets/javascripts/bootstrap-sprockets.js, and a concatenation at assets/javascripts/bootstrap.js.
Copies all upstream font files into assets/fonts/bootstrap.
Sets Bootstrap::BOOTSTRAP_SHA in version.rb to the branch sha.
This converter fully converts original LESS to SCSS. Conversion is automatic but requires instructions for certain transformations (see converter output). Please submit GitHub issues tagged with conversion.

**Comment by almasaeed2010** [comment]
This is what I was looking for. I am not sure though if the converter supports everything that LESS uses. I will need to test it first. Thanks!

**Comment by aguegu** [comment]
@almasaeed2010 

I am working on the scss version. And it is almost done. 

https://github.com/aguegu/AdminLTE

* all less have been convert to scss

And I can not help to add more trends/features in it

* bulid tool convert to gulp
* most plugins have been moved to bower.json
* the file structure have a big adjustment

Please check it out. And let me know what you think.

**Comment by cesarizu** [comment]
That's cool @aguegu !. I've been using http://github.com/karthilxg/AdminLTE for SASS support and it's working without problems too. The only thing that I think it needs (as well as yours) is to declare variables with `!default` so that they can be overridden when needed (for customizations).

**Comment by aguegu** [comment]
This could be a feature to work on. 

As this in a scss implementation, you may just rewrite the _varaibles in your favor and import the rest scss files. I am ok with refactorying the code, but I am so not a color tweaker... Changes only the syntax make it still trackable to the origin LESS styles. It is not that big different after all. I just completed my fork in a weekend. 

I wish @almasaeed2010 may look into this issue, there are too few `!default`, and too many `!important` in the source. 

I have register a bower package named admin-lte.scss, just stylesheet and js remained. All deps are left in config files. :) 

My fork has most completed. @almasaeed2010 , would you welcome my pull request? I sincerely doubt it, as there are too much changes. :(

And I have fix the js files by jshint. :)

**Pull request closed without merging**
