### PR TITLE
Use .on instead of .click for box actions

### PR DESCRIPTION
**Pull request by Soullivaneuh**
This is related to #302.

This will fix issue with ajax loaded html elements and not brake anything.

@almasaeed2010 please feel free to review my PR and comment the code if you have any question.

I don't know how you compile the `app.min.js` so I didn't touch it for the moment.

Thanks.

### CODE REVIEW

**Comment by almasaeed2010** [comment]
Hello,
I have implemented this in AdminLTE 2.1.0. Since I began working on, accepting PRs is bit more difficult. But you will see the change in the new version. I appreciate your contribution!

**Comment by Soullivaneuh** [comment]
@almasaeed2010 Glad to hear it. Where can I see your modifications? Already on git?

**Comment by almasaeed2010** [comment]
They will be available on Github with the alpha release of v2.1

**Comment by Soullivaneuh** [comment]
Hmm just for curiosity, why note commit directly modification for 2.1 on github with the master branch?

And you could keep a `2.0` branch for 2.0.x bugfix version, isn't it?

**Comment by almasaeed2010** [comment]
I usually push my commits to github when I have an alpha release ready. Many people tend to use the master repo to get their latest updates, which is unfortunate since the master repo is a development space. Nonetheless, we will see the recent changes soon.

Keeping more than one repo would give me too many tasks. As you might know, AdminLTE is just a fun project for me until I finish school. If by then I see more potential in it, I might dedicate more time towards it as necessary. Thanks.

**Comment by Soullivaneuh** [comment]
Ok I understand.

In any case, keeping AdminLTE updated directly on this repo will permit easier contributions! ;)

Regards.

**Pull request closed without merging**
