### PR TITLE
Fix animation bug with collapsed sidebar and treeview menu.

### PR DESCRIPTION
**Pull request by zviryatko**
Fix bug with treeview menu when sidebar is collapsed and you clicked to menu which already visible.

### CODE REVIEW

**Comment by iaesaudi** [comment]
Could you describe more about this bug, Because I can't figure the difference :disappointed:

**Comment by zviryatko** [comment]
1. Toggle left sidebar to icons view
2. Hover the mouse over any menu item that has submenu
3. Click on opened submenu header

**Comment by iaesaudi** [comment]
Still no difference :dizzy_face:

**Comment by zviryatko** [comment]
When you click on "UI Elements" the submenu is going to collapsing
example

**Comment by iaesaudi** [comment]
Great, I got it.

**Pull request merged**
