### PR TITLE
Fix the problem of loop binding resize event

### PR DESCRIPTION
**Pull request by lc-soft**
if body element has `layout-boxed` class，then resize the browser window will make
it more and more slowly, until completely unable to operate the browser.

### CODE REVIEW

**Comment by crperlin** [comment]
Can you provide  `camgif` ..slowly??thanks~

**Comment by lc-soft** [comment]
@crperlin you can try this example code:
``` html
<!DOCTYPE html>
<html>
<head>
<title>test</title>
<style>
.box {
  padding-top: 100px;
  font-size: 48px;
  text-align: center;
  background-color: green;
  height: 800px;
  width: 640px;
  margin: 0 auto;
}
</style>
</head>
<body>
  <div class="box">
    test
  </div>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript">
function onResize() {
  console.log('onresize');
  $(window).resize(onResize);
}
$(window).resize(onResize);
</script>
</body>
</html>
```
open in browser，and use the mouse to slowly adjust the size of the browser window, after a few seconds you'll see something like this effect:
qq 20151119182916

**Comment by lc-soft** [comment]
@crperlin 之前它的代码是每调用一次._fix() 函数就绑定一次 window 的 resize 事件，而处理 resize 事件时也是调用 _fix() 函数，当用鼠标拖动调整浏览器窗口大小时，resize 事件触发次数会由于这个的原因而成指数增长，调整几次后浏览器就卡了，页面刷新出现卡顿，关闭页面标签都要等好几秒。

之前遇到这问题时我还以为是浏览器的问题，换成火狐后问题依然存在，后来看到浏览器弹出提示框说 XXX.js 未响应，就试着看 app.js 的代码，然后就改了一下。

**Comment by crperlin** [comment]
@lc-soft  不错不错。我也改改。。。 我也改了lte的版本。。。https://github.com/crperlin/S-NEXT ; [Demo](http://crperlin.github.io/S-NEXT/)

**Comment by almasaeed2010** [comment]
Implemented in master.

Thanks!!

**Pull request closed without merging**
